import { version } from "../utils/interfaces";

const CEB_ANG_PULONG_SA_DIOS: version = "APSD-CEB";
const ENG_KJV_21: version = "KJ21";
const ENG_AMERICAN_STANDARD_VERSION: version = "ASV";
const ENG_AMPLIFIED_BIBLE: version = "AMP";
const ENG_AMPLIFIED_BIBLE_CLASSIC: version = "AMPC";
const ENG_BRG_BIBLE: version = "BRG";
const ENG_CHRISTIAN_STANDARD_BIBLE: version = "CSB";
const ENG_COMMON_ENLISH_BIBLE: version = "CEB";
const ENG_COMPLETE_JEWISH_BIBLE: version = "CJB";
const ENG_CONTEMPORARY_ENGLISH_VERSION: version = "CEV";
const ENG_DARBY_TRANSLATION: version = "BARBY";
const ENG_DISIPLES_LITERAL_NEW_TESTAMENT: version = "DLNT";
const ENG_DOUAY_RHEIMS_1899: version = "DRA";
const ENG_EASY_TO_READ_VERSION: version = "ERV";
const ENG_EVANGELICAL_HERITAGE_VERSION: version = "EHV";
const ENG_ENLISH_STANDARD_VERSION: version = "ESV";
const ENG_ENLISH_STANDARD_VERSION_ANGLICISED: version = "ESVUK";
const ENG_EXPANDED_BIBLE: version = "EXB";
const ENG_1599_GENEVA_BIBLE: version = "GNV";
const ENG_GODS_WORD_TRANSLATION: version = "GW";
const ENG_GOOD_NEWS_TRANSLATION: version = "GNT";
const ENG_HOLMAN_CHRISTIAN_STANDARD_BIBLE: version = "HCSB";
const ENG_INTERNATIONAL_CHILDRENS_BIBLE: version = "ICB";
const ENG_INTERNATIONAL_STANDARD_VERSION: version = "ISV";
const ENG_JB_PHILLIPS_NEW_TESTAMENT: version = "PHILLIPS";
const ENG_JUBILEE_BIBLE_2000: version = "JUB";
const ENG_KING_JAMES_VERSION: version = "KJV";
const ENG_AUTHORIZED_KING_JAMES_VERSION: version = "AKJV";
const ENG_LEXHAM_ENGLISH_BIBLE: version = "LEB";
const ENG_LIVING_BIBLE: version = "TLB";
const ENG_THE_MESSAGE: version = "MSG";
const ENG_MODERN_ENGLISH_VERSION: version = "MEV";
const ENG_MOUNCE_REVERSE_INTERLINEAR_NEW_TESTAMENT: version = "MOUNCE";
const ENG_NAMES_OF_GOD_BIBLE: version = "NOG";
const ENG_NEW_AMERICAN_BIBLE_REVISED_EDITION: version = "NABRE";
const ENG_NEW_AMERICAN_STANDARD_BIBLE: version = "NASB";
const ENG_NEW_AMERICAN_STANDARD_BIBLE_1995: version = "NASB1995";
const ENG_NEW_CATHOLIC_BIBLE: version = "NCB";
const ENG_NEW_CENTURY_VERSION: version = "NCV";
const ENG_NEW_ENGLISH_TRANSLATION: version = "NET";
const ENG_NEW_INTERNATIONAL_READERS_VERSION: version = "NIRV";
const ENG_NEW_INTERNATIONAL_VERSION: version = "NIV";
const ENG_NEW_INTERNATIONAL_VERSION_UK: version = "NIVUK";
const ENG_NEW_KING_JAMES_VERSION: version = "NKJV";
const ENG_NEW_LIFE_VERSION: version = "NLV";
const ENG_NEW_LIVING_TRANSLATION: version = "NIV";
const ENG_NEW_MATTHEW_BIBLE: version = "NMB";
const ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED: version = "NRSVA";
const ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED_CATHOLIC_EDITION: version =
  "NRSVACE";
const ILO_ANG_PULONG_SANG_DIOS_HLGN: version = "HLGN";
const TAG_ANG_BAGONG_TIPAN: version = "FSV";
const TAG_ANG_BIBLIA_1978: version = "ABTAG1978";
const TAG_ANG_BIBLIA_2001: version = "ABTAG2001";
const TAG_ANG_DATING_BIBLIYA_1905: version = "ADB1905";
const TAG_ANG_SALITA_NG_DIYOS_TCB: version = "ASND";
const TAG_ANG_SALITA_NG_DIYOS: version = "SND";
const TAG_MAGANDANG_BALITA: version = "MBBTAG";
const TAG_MAGANDANG_BALITA_DC: version = "MBBTAG-DC";
const BAYBAYIN_ANG_BAGONG_TIPAN: version = "baybay-FSV";
const BAYBAYIN_ANG_BIBLIA_1978: version = "baybay-ABTAG1978";
const BAYBAYIN_ANG_BIBLIA_2001: version = "baybay-ABTAG2001";
const BAYBAYIN_ANG_DATING_BIBLIYA_1905: version = "baybay-ADB1905";
const BAYBAYIN_ANG_SALITA_NG_DIYOS_TCB: version = "baybay-ASND";
const BAYBAYIN_ANG_SALITA_NG_DIYOS: version = "baybay-SND";
const BAYBAYIN_MAGANDANG_BALITA: version = "baybay-MBBTAG";
const BAYBAYIN_MAGANDANG_BALITA_DC: version = "baybay-MBBTAG-DC";

export {
  CEB_ANG_PULONG_SA_DIOS,
  ENG_KJV_21,
  ENG_AMERICAN_STANDARD_VERSION,
  ENG_AMPLIFIED_BIBLE,
  ENG_AMPLIFIED_BIBLE_CLASSIC,
  ENG_BRG_BIBLE,
  ENG_CHRISTIAN_STANDARD_BIBLE,
  ENG_COMMON_ENLISH_BIBLE,
  ENG_COMPLETE_JEWISH_BIBLE,
  ENG_CONTEMPORARY_ENGLISH_VERSION,
  ENG_DARBY_TRANSLATION,
  ENG_DISIPLES_LITERAL_NEW_TESTAMENT,
  ENG_DOUAY_RHEIMS_1899,
  ENG_EASY_TO_READ_VERSION,
  ENG_EVANGELICAL_HERITAGE_VERSION,
  ENG_ENLISH_STANDARD_VERSION,
  ENG_ENLISH_STANDARD_VERSION_ANGLICISED,
  ENG_EXPANDED_BIBLE,
  ENG_1599_GENEVA_BIBLE,
  ENG_GODS_WORD_TRANSLATION,
  ENG_GOOD_NEWS_TRANSLATION,
  ENG_HOLMAN_CHRISTIAN_STANDARD_BIBLE,
  ENG_INTERNATIONAL_CHILDRENS_BIBLE,
  ENG_INTERNATIONAL_STANDARD_VERSION,
  ENG_JB_PHILLIPS_NEW_TESTAMENT,
  ENG_JUBILEE_BIBLE_2000,
  ENG_KING_JAMES_VERSION,
  ENG_AUTHORIZED_KING_JAMES_VERSION,
  ENG_LEXHAM_ENGLISH_BIBLE,
  ENG_LIVING_BIBLE,
  ENG_THE_MESSAGE,
  ENG_MODERN_ENGLISH_VERSION,
  ENG_MOUNCE_REVERSE_INTERLINEAR_NEW_TESTAMENT,
  ENG_NAMES_OF_GOD_BIBLE,
  ENG_NEW_AMERICAN_BIBLE_REVISED_EDITION,
  ENG_NEW_AMERICAN_STANDARD_BIBLE,
  ENG_NEW_AMERICAN_STANDARD_BIBLE_1995,
  ENG_NEW_CATHOLIC_BIBLE,
  ENG_NEW_CENTURY_VERSION,
  ENG_NEW_ENGLISH_TRANSLATION,
  ENG_NEW_INTERNATIONAL_READERS_VERSION,
  ENG_NEW_INTERNATIONAL_VERSION,
  ENG_NEW_INTERNATIONAL_VERSION_UK,
  ENG_NEW_KING_JAMES_VERSION,
  ENG_NEW_LIFE_VERSION,
  ENG_NEW_LIVING_TRANSLATION,
  ENG_NEW_MATTHEW_BIBLE,
  ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED,
  ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED_CATHOLIC_EDITION,
  ILO_ANG_PULONG_SANG_DIOS_HLGN,
  TAG_ANG_BAGONG_TIPAN,
  TAG_ANG_BIBLIA_1978,
  TAG_ANG_BIBLIA_2001,
  TAG_ANG_DATING_BIBLIYA_1905,
  TAG_ANG_SALITA_NG_DIYOS_TCB,
  TAG_ANG_SALITA_NG_DIYOS,
  TAG_MAGANDANG_BALITA,
  TAG_MAGANDANG_BALITA_DC,
  BAYBAYIN_ANG_BAGONG_TIPAN,
  BAYBAYIN_ANG_BIBLIA_1978,
  BAYBAYIN_ANG_BIBLIA_2001,
  BAYBAYIN_ANG_DATING_BIBLIYA_1905,
  BAYBAYIN_ANG_SALITA_NG_DIYOS_TCB,
  BAYBAYIN_ANG_SALITA_NG_DIYOS,
  BAYBAYIN_MAGANDANG_BALITA,
  BAYBAYIN_MAGANDANG_BALITA_DC,
};
