const CEB_ANG_PULONG_SA_DIOS = "APSD-CEB"
const ENG_KJV_21 = "KJ21"
const ENG_AMERICAN_STANDARD_VERSION = "ASV"
const ENG_AMPLIFIED_BIBLE = "AMP"
const ENG_AMPLIFIED_BIBLE_CLASSIC = "AMPC"
const ENG_BRG_BIBLE = "BRG"
const ENG_CHRISTIAN_STANDARD_BIBLE = "CSB"
const ENG_COMMON_ENLISH_BIBLE = "CEB"
const ENG_COMPLETE_JEWISH_BIBLE = "CJB"
const ENG_CONTEMPORARY_ENGLISH_VERSION = "CEV"
const ENG_DARBY_TRANSLATION = "BARBY"
const ENG_DISIPLES_LITERAL_NEW_TESTAMENT = "DLNT"
const ENG_DOUAY_RHEIMS_1899 = "DRA"
const ENG_EASY_TO_READ_VERSION = "ERV"
const ENG_EVANGELICAL_HERITAGE_VERSION = "EHV"
const ENG_ENLISH_STANDARD_VERSION = "ESV"
const ENG_ENLISH_STANDARD_VERSION_ANGLICISED = "ESVUK"
const ENG_EXPANDED_BIBLE = "EXB"
const ENG_1599_GENEVA_BIBLE = "GNV"
const ENG_GODS_WORD_TRANSLATION = "GW"
const ENG_GOOD_NEWS_TRANSLATION = "GNT"
const ENG_HOLMAN_CHRISTIAN_STANDARD_BIBLE = "HCSB"
const ENG_INTERNATIONAL_CHILDRENS_BIBLE = "ICB"
const ENG_INTERNATIONAL_STANDARD_VERSION = "ISV"
const ENG_JB_PHILLIPS_NEW_TESTAMENT = "PHILLIPS"
const ENG_JUBILEE_BIBLE_2000 = "JUB"
const ENG_KING_JAMES_VERSION = "KJV"
const ENG_AUTHORIZED_KING_JAMES_VERSION = "AKJV"
const ENG_LEXHAM_ENGLISH_BIBLE = "LEB"
const ENG_LIVING_BIBLE = "TLB"
const ENG_THE_MESSAGE = "MSG"
const ENG_MODERN_ENGLISH_VERSION = "MEV"
const ENG_MOUNCE_REVERSE_INTERLINEAR_NEW_TESTAMENT = "MOUNCE"
const ENG_NAMES_OF_GOD_BIBLE = "NOG"
const ENG_NEW_AMERICAN_BIBLE_REVISED_EDITION = "NABRE"
const ENG_NEW_AMERICAN_STANDARD_BIBLE = "NASB"
const ENG_NEW_AMERICAN_STANDARD_BIBLE_1995 = "NASB1995"
const ENG_NEW_CATHOLIC_BIBLE = "NCB"
const ENG_NEW_CENTURY_VERSION = "NCV"
const ENG_NEW_ENGLISH_TRANSLATION = "NET"
const ENG_NEW_INTERNATIONAL_READERS_VERSION = "NIRV"
const ENG_NEW_INTERNATIONAL_VERSION = "NIV"
const ENG_NEW_INTERNATIONAL_VERSION_UK = "NIVUK"
const ENG_NEW_KING_JAMES_VERSION = "NKJV"
const ENG_NEW_LIFE_VERSION = "NLV"
const ENG_NEW_LIVING_TRANSLATION = "NIV"
const ENG_NEW_MATTHEW_BIBLE = "NMB"
const ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED = "NRSVA"
const ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED_CATHOLIC_EDITION = "NRSVACE"
const ILO_ANG_PULONG_SANG_DIOS_HLGN = "HLGN"
const TAG_ANG_BAGONG_TIPAN = "FSV"
const TAG_ANG_BIBLIA_1978 = "ABTAG1978"
const TAG_ANG_BIBLIA_2001 = "ABTAG2001"
const TAG_ANG_DATING_BIBLIYA_1905 = "ADB1905"
const TAG_ANG_SALITA_NG_DIYOS_TCB = "ASND"
const TAG_ANG_SALITA_NG_DIYOS = "SND"
const TAG_MAGANDANG_BALITA = "MBBTAG"
const TAG_MAGANDANG_BALITA_DC = "MBBTAG-DC"

module.exports = {
	CEB_ANG_PULONG_SA_DIOS,
	ENG_KJV_21,
	ENG_AMERICAN_STANDARD_VERSION,
	ENG_AMPLIFIED_BIBLE,
	ENG_AMPLIFIED_BIBLE_CLASSIC,
	ENG_BRG_BIBLE,
	ENG_CHRISTIAN_STANDARD_BIBLE,
	ENG_COMMON_ENLISH_BIBLE,
	ENG_COMPLETE_JEWISH_BIBLE,
	ENG_CONTEMPORARY_ENGLISH_VERSION,
	ENG_DARBY_TRANSLATION,
	ENG_DISIPLES_LITERAL_NEW_TESTAMENT,
	ENG_DOUAY_RHEIMS_1899,
	ENG_EASY_TO_READ_VERSION,
	ENG_EVANGELICAL_HERITAGE_VERSION,
	ENG_ENLISH_STANDARD_VERSION,
	ENG_ENLISH_STANDARD_VERSION_ANGLICISED,
	ENG_EXPANDED_BIBLE,
	ENG_1599_GENEVA_BIBLE,
	ENG_GODS_WORD_TRANSLATION,
	ENG_GOOD_NEWS_TRANSLATION,
	ENG_HOLMAN_CHRISTIAN_STANDARD_BIBLE,
	ENG_INTERNATIONAL_CHILDRENS_BIBLE,
	ENG_INTERNATIONAL_STANDARD_VERSION,
	ENG_JB_PHILLIPS_NEW_TESTAMENT,
	ENG_JUBILEE_BIBLE_2000,
	ENG_KING_JAMES_VERSION,
	ENG_AUTHORIZED_KING_JAMES_VERSION,
	ENG_LEXHAM_ENGLISH_BIBLE,
	ENG_LIVING_BIBLE,
	ENG_THE_MESSAGE,
	ENG_MODERN_ENGLISH_VERSION,
	ENG_MOUNCE_REVERSE_INTERLINEAR_NEW_TESTAMENT,
	ENG_NAMES_OF_GOD_BIBLE,
	ENG_NEW_AMERICAN_BIBLE_REVISED_EDITION,
	ENG_NEW_AMERICAN_STANDARD_BIBLE,
	ENG_NEW_AMERICAN_STANDARD_BIBLE_1995,
	ENG_NEW_CATHOLIC_BIBLE,
	ENG_NEW_CENTURY_VERSION,
	ENG_NEW_ENGLISH_TRANSLATION,
	ENG_NEW_INTERNATIONAL_READERS_VERSION,
	ENG_NEW_INTERNATIONAL_VERSION,
	ENG_NEW_INTERNATIONAL_VERSION_UK,
	ENG_NEW_KING_JAMES_VERSION,
	ENG_NEW_LIFE_VERSION,
	ENG_NEW_LIVING_TRANSLATION,
	ENG_NEW_MATTHEW_BIBLE,
	ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED,
	ENG_NEW_REVISED_STANDARD_VERSION_ANGLICISED_CATHOLIC_EDITION,
	ILO_ANG_PULONG_SANG_DIOS_HLGN,
	TAG_ANG_BAGONG_TIPAN,
	TAG_ANG_BIBLIA_1978,
	TAG_ANG_BIBLIA_2001,
	TAG_ANG_DATING_BIBLIYA_1905,
	TAG_ANG_SALITA_NG_DIYOS_TCB,
	TAG_ANG_SALITA_NG_DIYOS,
	TAG_MAGANDANG_BALITA,
	TAG_MAGANDANG_BALITA_DC
}